### ISSUE TITLE
Update of norns to 0.1.6 on PyPI

### ISSUE THREAD

**Issue by msbentsen** [simonvh/norns#8]
Hi, I saw that you fixed the deprecation error of `collections` in norns version 0.1.6 here and on bioconda (thank you for maintaining!). Would you be able to update norns to 0.1.6 on PyPI as well? I am a frequent user of gimmemotifs and just ended up in a very specific scenario on python 3.10, where I installed gimmemotifs with pip, but pip then only fetched norns=0.1.5 on install, leading to an error on import. Would be great to still be able to install with pip.

**Comment by simonvh** [comment]
Sure! https://pypi.org/project/norns/0.1.6/

**Comment by msbentsen** [comment]
Amazing, thank you for the swift update!
